# HordeComms is built on the foundation of Dishorde by LakeYS
# Please consider supporting the original creator who made this project possible
# HordeComms enhancements are provided freely to the community

github: LakeYS
patreon: LakeYS
